name: test

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main' # exclude main branch, since deploy workflow triggers on main, and calls the test workflow inside of it already
    tags-ignore:
      - v* # exclude tags, since deploy workflow triggers on tags, and calls the test workflow inside of it already

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # per [workflow] x [branch, tag]
  cancel-in-progress: true #  cancel workflows for non-latest commits

jobs:
  suite:
    uses: ./.github/workflows/.test.yml
    secrets:
      ASK_AUTH_CHALLENGE_EXAMPLE_EMAIL: ${{ secrets.ASK_AUTH_CHALLENGE_EXAMPLE_EMAIL }}
      ASK_AUTH_CHALLENGE_EXAMPLE_DIRECTORY_UUID: ${{ secrets.ASK_AUTH_CHALLENGE_EXAMPLE_DIRECTORY_UUID }}
      ASK_AUTH_CHALLENGE_EXAMPLE_CLIENT_TOKEN: ${{ secrets.ASK_AUTH_CHALLENGE_EXAMPLE_CLIENT_TOKEN }}
